services:
  # Il Web Service (Node.js + Frontend)
  - type: web
    name: mentormatch-app
    env: docker
    plan: free
    region: frankfurt # O 'oregon', 'singapore', etc.
    branch: main # Impostiamo il branch su cui stiamo lavorando
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mentormatch-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true # Render generer√† una chiave sicura per noi

databases:
  - name: mentormatch-db
    plan: free
    databaseName: mentormatch
    user: admin